Repository codeRIT/brickhack.io, pull requests merged in 2021-02, with the labels that each got.

#1139 Added dynamic schedule
  index.html
  index.js
  sass/main.scss
Labels: BH7

#1143 Update FAQ with swag eligibility
  index.html
  sass/main.scss
Labels: BH7

#1147 Hotfix timezones on schedule
  index.js
Labels: BH7

#1144 Change M&T Tech & M&T Bank
  assets/sponsors/logos/mtbank-white.svg
  assets/sponsors/logos/mtbank.svg
  assets/sponsors/logos/mttech-white.svg
  assets/sponsors/logos/mttech.svg
  index.html
  sass/main.scss
Labels: BH7

#1145 BrickHack 7 Updates
  assets/sponsors/logos/mtbank-white.svg
  assets/sponsors/logos/mtbank.svg
  assets/sponsors/logos/mttech-white.svg
  assets/sponsors/logos/mttech.svg
  index.html
  index.js
  sass/main.scss
Labels: BH7, release

#1148 Schedule dates are shown in local timezone
  index.html
  index.js
Labels: BH7

#1151 Adjusting gallery modal design
  gallery.html
  sass/gallery.scss
Labels: BH7

#1158 Added event sorting
  index.js
Labels: BH7

#1160 New schedule design with pre-event workshop support (no mobile)
  index.html
  index.js
  sass/main.scss
Labels: BH7

#1164 Added more sponsor logos
  assets/sponsors/logos/dolbyio-white.svg
  assets/sponsors/logos/dolbyio.svg
  assets/sponsors/logos/northrop-white.svg
  assets/sponsors/logos/northrop.svg
  assets/sponsors/logos/simonecenter-white.svg
  assets/sponsors/logos/simonecenter.svg
  index.html
  sass/main.scss
Labels: BH7

#1163 Schedule 2.0 Mobile
  sass/main.scss
Labels: BH7

#1169 Fixing gallery modal size and background scrolling
  gallery.html
  gallery.js
  sass/gallery.scss
Labels: BH7, gallery

#1170 "Show more" buttons share tab colors
  sass/main.scss
Labels: BH7

#1155 Add discord button to hero
  index.html
  sass/main.scss
Labels: BH7

#1176 Fix Discord link
  index.html
Labels: BH7

#1174 BrickHack 7 Updates
  gallery.html
  gallery.js
  index.html
  sass/gallery.scss
  sass/main.scss
Labels: BH7, release

#1178 Revert "Add discord button to hero (#1155)"
  index.html
  sass/main.scss
Labels: BH7

#1179 BrickHack 7 Updates
  index.html
  sass/main.scss
Labels: BH7

#1181 fix: Feb 20 schedule page shouldn't have a hover effect
  sass/main.scss
Labels: BH7

#1183 BrickHack 7 Updates
  sass/main.scss
Labels: BH7, release

#1152 Footer hover effect
  index.html
  sass/main.scss
Labels: BH7

#1184 Add discord to site (again)
  index.html
  sass/main.scss
Labels: BH7

#1185 BrickHack 7 Upates
  index.html
  sass/main.scss
Labels: BH7, release

#1187 Set schedule tab based on date
  index.html
  index.js
Labels: BH7

#1188 BrickHack 7 Updates
  index.html
  index.js
Labels: BH7, release

#1190 Fix undefined function in schedule
  index.js
Labels: BH7

#1191 Update BrickHack 7
  index.js
Labels: BH7

#1193 Post event website
  assets/post-event/closing-crop.gif
  assets/post-event/closing.gif
  assets/post-event/closing.mp4
  event.html
  event.js
  index.html
  index.js
  sass/event.scss
Labels: BH7

#1196 Fix scaling and responsiveness, Safari bug
  index.js
  sass/event.scss
Labels: BH7

#1197 BrickHack 7 Post-Site Updates
  index.js
  sass/event.scss
Labels: BH7, release
